ocf/etc

- Jenkinsfile
- Makefile
A basic Jenkinsfile that runs tests. Probably should have included this in the original commit.
This is actually the exact same Jenkinsfile from the utils repo since we're doing basically the same thing.
> Add Jenkinsfile

- configs/hours.yaml
Added early lab closure for VSA Resume Workshop. Validated with make
> Early Lab Closure 3/19/2019 for Cal VSA Resume Workshop

- configs/lab_status.yaml
- configs/validate.yaml
- schemas/lab_status.schema.json
Fixes #19 
After this is merged, will test and submit the corresponding PR to ocfweb to read from this file.
> Add lab_status.yaml

- configs/staff_hours.yaml
Adding myself to staff hours with @ethanhs
> Staff hours for kmo on Thurs

- configs/staff_hours.yaml
It me, adding myself to the hours of staffing, I shall take up my sword and protect our holy kingdom if you shall allow it.
> staff ahoras

- configs/staff_hours.yaml
First attempt failed checks (see #35 for more info). This hopefully should work.
> Add bencuan to Friday staff hours (Attempt 2)

- configs/staff_hours.yaml
> move shmaeng down

- configs/staff_hours.yaml
obviously jenkins is not gonna run rn but i ran tests locally
> uncancel cooperc staff hours

- configs/hours.yaml
changed hours for early lab closure
> Changed Hours for Facebook Talk

- configs/staff_hours.yaml
> Deleted my staff hours

- configs/staff_hours.yaml
Changing times from 1PM-2PM to 2PM-4PM.
> Update staff hours for kmo

- configs/staff_hours.yaml
> Update bencuan staff hours

- configs/staff_hours.yaml
Reduce staff hours for kmo in Spring 2020
> Reduce staff hours for kmo (sp20)

- configs/staff_hours.yaml
> Revert "Update staff_hours.yaml"

- configs/staff_hours.yaml
> cancel my staff hours this week

- configs/staff_hours.yaml
> cancel March 6th for kmo

- configs/staff_hours.yaml
> Add more hours in staff hours

- configs/hours.yaml
Wanted to make this PR before it gets lost
> Close lab until next BoD

- configs/hours.yaml
> close the lab through april 7th

- configs/hours.yaml
The shelter-in-place will continue until at least this time.
> close lab until May 3

- configs/hours.yaml
https://registrar.berkeley.edu/sites/default/files/pdf/UCB_AcademicCalendar_2020-21_V2.pdf
> Split "Public Health Closure" into Summer Break

- configs/vhost-app.conf
> add wslradio apphost socket

- configs/vhost-app.conf
They will be transitioning to a Django app
> Add launchpad app vhost

- configs/vhost-app.conf
This is something I discussed on #rebuild. It would be nice to trial giving users app vhosts and see what comes out of it.
> Add eashman vhost app

- configs/vhost.conf
added 2020-07-28 kmo personal email
> Add mappingforej.b.e vhost for ejmp

- configs/vhost.conf
> Remove vhost from datagood

- configs/vhost.conf
> add legends vhost

- configs/staff_hours.yaml
> Change jaw staff hours to Tuesday

- configs/vhost-mail.conf
> multiple mail vhosts

- configs/vhost-app.conf
This is required for their app. I'm currently baking in support for this on the build-vhosts side.
> add websocket flag to hkn tutoring app vhost

- configs/vhost-app.conf
They want to move their site to OCF again
> Create tbp-dev app vhost

- configs/vhost.conf
> add combatrobotics to vhost

- configs/staff_hours.yaml
adding all staff hours for spring 2021 (branch name now a misnomer)
> staff hours sp21

- configs/staff_hours.yaml
I probably won't have time to hold staff hours at a set time :(
> Remove my staff hours for the summer

- configs/staff_hours.yaml
Can't really commit to this at a reliable time it seems
> Remove my staff hours for summer

- configs/vhost-app.conf
> Fix trailing space

- configs/vhost.conf
> Add abw vhost

- configs/staff_hours.yaml
So I don't forget to roll my cancel back, don't push yet
> Prepping PR for after Thursday

- configs/vhost.conf
> Add stemcellcenter.berkeley.edu

- configs/vhost-mail.conf
> Add ifb mail vhost

- configs/vhost-mail.conf
> Add btc mail vhost

- configs/vhost-mail.conf
> Add calasa mail vhost

- configs/vhost-mail.conf
> Add asl mail vhost

- configs/vhost.conf
> Add define vhost

- configs/hours.yaml
> Revert "Add Veteran's day closure"

- configs/vhost-mail.conf
> Add calproductspace mail vhost

- configs/vhost-app.conf
Request is made on behalf of the LEAD center.
> Add app.lead

- configs/vhost-mail.conf
- configs/vhost.conf
> Change bmf to mfb vhosts

- configs/vhost.conf
> Add apsa vhost

- configs/vhost-mail.conf
> Add capclub mail vhost

- configs/staff_hours.yaml
re-add yourself if you're still interested in hosting staff hours!
> update staff hours sp22

- configs/vhost-mail.conf
> Add blit vhost

- configs/vhost.conf
> Add cqg vhost

- configs/vhost.conf
> Add housingcomm vhost

- configs/vhost-mail.conf
> Add eggster mail vhost

- configs/vhost-mail.conf
> Add 4dcapital mail vhost

- configs/vhost-mail.conf
> Add skateboarding mailvhost

- configs/vhost-mail.conf
> Add globalinvestors mail vhost

- configs/vhost-mail.conf
> Add fedchallenge mailvhost

- configs/vhost-mail.conf
> Add pmh mail vhost

- configs/vhost-mail.conf
> Add pab mailvhost

- configs/vhost-mail.conf
> Add cqg mailvhost

- configs/vhost-mail.conf
> Add enviro mailvhost

- configs/vhost.conf
> Add studiogeo vhost

- configs/vhost.conf
> Add reddie vhost

- configs/vhost.conf
> Add biox vhost

- configs/vhost-mail.conf
> Add biox mailvhost

- configs/vhost.conf
rt#11499
Additional host added, hostmaster ticket RITM0086559
> Add reddie ischool vhost

- configs/vhost-mail.conf
> Add beam mail host

- configs/vhost.conf
> Added psychedelics as bcsp alias

- configs/vhost-mail.conf
> Add calcodeology mailvhost

- configs/vhost-mail.conf
- configs/vhost.conf
> Add sensibility web and mail vhost

- configs/vhost-mail.conf
> Add bessa mailvhost

- configs/hours.yaml
- requirements-dev.txt
- schemas/hours.schema.json
Should be merged AFTER changes to ocflib, otherwise ocfweb will fail. Merge this first (and see for more information): https://github.com/ocf/ocflib/pull/246
(CI test should also be run again as at present it will fail due to ocflib error)
> Close regularly on Sundays

- configs/vhost.conf
> Disable hsc vhost

- configs/vhost.conf
> Add grc vhost

- configs/vhost.conf
> Add hellmanlab vhost

- configs/vhost-mail.conf
> Add hsc mailvhost

- configs/vhost-mail.conf
- configs/vhost.conf
> Add CR mailvhost

- configs/vhost-mail.conf
> Rename combatrobotics mailvhost

- configs/staff_hours.yaml
add my staff hours into the list
> add staff hours

- configs/vhost-mail.conf
> Add bsgsa mailvhost

- configs/vhost.conf
> Add dgab vhost

- configs/vhost-mail.conf
> Add powerbayarea mailvhost

- configs/vhost.conf
> Add detrash vhost

- configs/staff_hours.yaml
> add bryli to staff hours

- configs/staff_hours.yaml
> Add lucdar to staff hours

- configs/staff_hours.yaml
> Add jaysag to staff_hours.yaml

- configs/vhost.conf
> Add poker vhost

- configs/staff_hours.yaml
hello I am newstaff
adding myself to staff hours
> add trinityc to staff_hours.yaml

- configs/vhost-app.conf
> Disable invest appvhost

- configs/vhost.conf
Add calico.cs.b.e and redirect calico.b.e to it
> Update calico.cs.b.e vhost

- configs/vhost-mail.conf
> add substrate mail vhost

- configs/lab_status.yaml
See [ocfweb#817](https://github.com/ocf/ocfweb/pull/817/)
> Update main page subdomain announcement

- configs/staff_hours.yaml
remove my Wednesday staff hours from 11 AM - 12 PM
> Remove staff hours

- configs/vhost.conf
> Move swps to studentorg.be

- configs/vhost-mail.conf
- configs/vhost.conf
https://rt.ocf.berkeley.edu/Ticket/Display.html?id=13525
> Added domains for USI

- configs/vhost-app.conf
> Add apphost mirrors

- configs/vhost-app.conf
> add entry to vhost-app.conf

- configs/vhost-app.conf
- configs/vhost.conf
adding hivemind but for autolab
> update vhost.conf for status.autolab

- configs/vhost-app.conf
- configs/vhost.conf
> Revert "update vhost.conf for status.autolab"

- configs/vhost.conf
RT#13894
Lmk if anything else is needed
> Add `tikvah` RSO to vhost.conf

- configs/vhost.conf
fixed potential syntax error in old rt ticket. The website is not working for some reason
> Update vhost.conf, 
